utils::globalVariables(c('.',
                        'code_insee', 'dept', 'annee', 'effectif', 'coursdo',
                        'esp_code_alternatif', 'esp_id',
                        'lot_poissons', 'lop_id', 'lop_pre_id', 'lop_effectif', 'lop_esp_id',
                        'operation_ipr', 'ipr', 'classe_ipr', 'opi_ipr', 'opi_ope_id',
                        'opi_param_surf', 'opi_param_sbv', 'opi_param_ds', 'opi_param_lar', 'opi_param_pent',
                        'opi_param_prof', 'opi_param_alt', 'opi_param_tjuillet', 'opi_param_tjanvier',
                        'opi_param_bassin',
                        'prelevement_elementaire', 'pre_id', 'pre_ope_id',
                        'operation', 'ope_id', 'ope_pop_id', 'operation_objectif', 'ope_date', 'opo_ope_id',
                        'opo_obj_id', 'obj_id',
                        'point_prelevement', 'pop_sta_id', 'pop_id', 'pop_libelle_wama', 'libelle_point', 'pop_enh_id',
                        'station', 'sta_com_code_insee', 'sta_libelle_sandre', 'libelle_station',
                        'sta_id',
                        'ref_espece',
                        'ref_unite_hydrographique', 'unh_libelle', 'unh_code_sandre', 'unh_libelle_sandre'))
