utils::globalVariables(c('.',
                        'code_insee', 'dept', 'annee', 'effectif', 'coursdo',
                        'esp_code_alternatif', 'esp_id',
                        'lot_poissons', 'lop_id', 'lop_pre_id', 'lop_effectif', 'lop_esp_id',
                        'operation_ipr', 'ipr', 'classe_ipr', 'opi_ipr', 'opi_ope_id',
                        'opi_param_surf', 'opi_param_sbv', 'opi_param_ds', 'opi_param_lar', 'opi_param_pent',
                        'opi_param_prof', 'opi_param_alt', 'opi_param_tjuillet', 'opi_param_tjanvier',
                        'opi_param_bassin',
                        'prelevement_elementaire', 'pre_id', 'pre_ope_id',
                        'operation', 'ope_id', 'ope_pop_id', 'operation_objectif', 'ope_date', 'opo_ope_id',
                        'ope_surface_calculee', 'opo_obj_id', 'obj_id',
                        'point_prelevement', 'pop_sta_id', 'pop_id', 'pop_libelle_wama', 'libelle_point', 'pop_enh_id',
                        'pop_libelle',
                        'station', 'sta_com_code_insee', 'sta_libelle_sandre', 'libelle_station',
                        'sta_id', 'opi_ner', 'ner', 'dti',
                        'ref_espece',
                        'tlo_libelle',
                        'mei_taille',
                        'cli_altitude_min', 'cli_borne_inf', 'cli_libelle',
                        'ref_unite_hydrographique', 'unh_libelle', 'unh_code_sandre', 'unh_libelle_sandre',
                        'ABLab', 'VANab',
                        'bon derniere_annee', 'n_sta', 'pas_bon', 'premiere_annee', 'derniere_annee', 'bon',
                        '..density..', 'mei_poids',
                        'V6', 'V7', 'V8', 'V9', 'x', 'scaled', 'n_sup_seuil', 'tp_esp',
                        'typ_code_epsg', 'richesse', 'mop_id', 'odp_mop_id', 'odp_ope_id',
                        'operation_description_peche', 'ref_moyen_prospection', 'ope_pro_id', 'pro_id',
                        'typ_libelle_sandre', 'ref_type_projection', 'typ_id',
                        'col_ext'))
